eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  dashboard:
    path: /eureka-ui

spring:
  application:
    name: service-discovery
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8761